name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
        env:
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PODCAST_DOCUMENT: ${{ secrets.FIREBASE_PODCAST_DOCUMENT }}
